/*
  tours-data.js — Mây Ngàn Travel
  TOÀN BỘ dữ liệu tour — sửa ở đây là cập nhật toàn site

  destSlug — slug khớp với data-dest trên chip HTML:
  'sapa' | 'yty' | 'mocchau' | 'bachha' | 'mcc' | 'taxua'
  | 'hagiang' | 'caobang' | 'backan'
  Nhiều điểm cách nhau bằng dấu cách: 'mcc sapa'
*/

const TOURS_DATA = [

  /* ── SAPA ────────────────────────────────────────────── */
  {
    id: 'MNSP01',
    name: 'Tour Du lịch Sa Pa 3N2Đ',
    img: '../images/1_Sapa/MNSP01/MNSP01_01.jpg',
    imgAlt: 'Tour Du lịch Sa Pa 3N2Đ',
    duration: '3N2Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2990000,
    priceOld: null,
    isHot: true,
    isNew: false,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Sapa',
    otherDests: [],
    link: './chi_tiet/MNSP01.html',
    destSlug: 'sapa'
  },
  {
    id: 'MNSP02',
    name: 'Tour Sapa - Mộc Châu - Điện Biên - Lai Châu 5N4Đ',
    img: '../images/1_Sapa/MNSP02/MNSP02_01.jpg',
    imgAlt: 'Tour Sapa - Mộc Châu - Điện Biên - Lai Châu 5N4Đ',
    duration: '5N4Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 7018000,
    priceOld: null,
    isHot: false,
    isNew: true,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Sapa',
    otherDests: ['Điện Biên', 'Lai Châu', 'Mộc Châu'],
    link: './chi_tiet/MNSP02.html',
    destSlug: 'sapa mocchau'
  },
  {
    id: 'MNSP03',
    name: 'Tour Sapa - Lai Châu - Điện Biên - Mộc Châu - Đền Bảo Hà 5N5Đ',
    img: '../images/1_Sapa/MNSP03/MNSP03_01.jpg',
    imgAlt: 'Tour Sapa - Lai Châu - Điện Biên - Mộc Châu - Đền Bảo Hà 5N5Đ',
    duration: '5N5Đ',
    transport: 'Máy bay',
    departure: 'Hồ Chí Minh',
    price: 14333000,
    priceOld: null,
    isHot: false,
    isNew: true,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Sapa',
    otherDests: ['Lai Châu', 'Điện Biên', 'Mộc Châu'],
    link: './chi_tiet/MNSP03.html',
    destSlug: 'sapa mocchau'
  },

  /* ── Y TÝ ─────────────────────────────────────────────── */
  {
    id: 'MNYT01',
    name: 'Tour Y Tý 2N1Đ',
    img: '../images/2_YTy/MNYT01/MNYT01_01.jpg',
    imgAlt: 'Tour Y Tý 2N1Đ',
    duration: '2N1Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2178000,
    priceOld: null,
    isHot: true,
    isNew: false,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Y Tý',
    otherDests: [],
    link: './chi_tiet/MNYT01.html',
    destSlug: 'yty'
  },
  {
    id: 'MNYT02',
    name: 'Tour Y Tý - Bắc Hà 3N2Đ',
    img: '../images/2_YTy/MNYT02/MNYT02_01.jpg',
    imgAlt: 'Tour Y Tý - Bắc Hà 3N2Đ',
    duration: '3N2Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 3718000,
    priceOld: null,
    isHot: false,
    isNew: true,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Y Tý',
    otherDests: ['Bắc Hà'],
    link: './chi_tiet/MNYT02.html',
    destSlug: 'yty bachha'
  },

  /* ── MỘC CHÂU ────────────────────────────────────────── */
  {
    id: 'MNMC01',
    name: 'Tour Mộc Châu 2N1Đ',
    img: '../images/3_MocChau/MNMC01/MNMC01_03.jpg',
    imgAlt: 'Tour Mộc Châu 2N1Đ',
    duration: '2N1Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2180000,
    priceOld: null,
    isHot: true,
    isNew: false,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Mộc Châu',
    otherDests: [],
    link: './chi_tiet/MNMC01.html',
    destSlug: 'mocchau'
  },
  {
    id: 'MNMC02',
    name: 'Tour Mộc Châu - Tà Xùa 3N2Đ',
    img: '../images/3_MocChau/MNMC02/MNMC02_01.jpg',
    imgAlt: 'Tour Mộc Châu - Tà Xùa 3N2Đ',
    duration: '3N2Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2800000,
    priceOld: null,
    isHot: false,
    isNew: false,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Mộc Châu',
    otherDests: ['Tà Xùa'],
    link: './chi_tiet/MNMC02.html',
    destSlug: 'mocchau taxua'
  },
  {
    id: 'MNMC03',
    name: 'Tour Mộc Châu - Điện Biên 3N2Đ',
    img: '../images/3_MocChau/MNMC03/MNMC03_01.jpg',
    imgAlt: 'Tour Mộc Châu - Điện Biên 3N2Đ',
    duration: '3N2Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 3498000,
    priceOld: null,
    isHot: false,
    isNew: false,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Mộc Châu',
    otherDests: ['Điện Biên'],
    link: './chi_tiet/MNMC03.html',
    destSlug: 'mocchau'
  },

  /* ── BẮC HÀ ──────────────────────────────────────────── */
  {
    id: 'MNBH01',
    name: 'Tour Bắc Hà - Tả Van Chư 2N1Đ',
    img: '../images/4_BacHa/MNBH01/MNBH01_01.jpg',
    imgAlt: 'Tour Bắc Hà - Tả Van Chư 2N1Đ',
    duration: '2N1Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2398000,
    priceOld: null,
    isHot: false,
    isNew: true,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Bắc Hà',
    otherDests: [],
    link: './chi_tiet/MNBH01.html',
    destSlug: 'bachha'
  },

  /* ── MÙ CANG CHẢI ────────────────────────────────────── */
  {
    id: 'MNM201',
    name: 'Tour Mù Cang Chải 4N3Đ',
    img: '../images/5_MuCangChai/MNM201/MNM201_01.jpg',
    imgAlt: 'Tour Mù Cang Chải 4N3Đ',
    duration: '4N3Đ',
    transport: 'Máy bay',
    departure: 'Hồ Chí Minh',
    price: 8680000,
    priceOld: null,
    isHot: false,
    isNew: false,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Mù Cang Chải',
    otherDests: [],
    link: './chi_tiet/MNM201.html',
    destSlug: 'mcc'
  },
  {
    id: 'MNM202',
    name: 'Tour Mù Cang Chải 3N2Đ',
    img: '../images/5_MuCangChai/MNM202/MNM202_01.jpg',
    imgAlt: 'Tour Mù Cang Chải 3N2Đ',
    duration: '3N2Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 3280000,
    priceOld: null,
    isHot: true,
    isNew: false,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Mù Cang Chải',
    otherDests: [],
    link: './chi_tiet/MNM202.html',
    destSlug: 'mcc'
  },
  {
    id: 'MNM203',
    name: 'Tour Mù Cang Chải – Sapa 3N2Đ',
    img: '../images/5_MuCangChai/MNM203/MNM203_01.jpg',
    imgAlt: 'Tour Mù Cang Chải – Sapa 3N2Đ',
    duration: '3N2Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2527000,
    priceOld: 2660000,
    isHot: false,
    isNew: false,
    isSale: true,
    region: 'Tây Bắc',
    primaryDest: 'Mù Cang Chải',
    otherDests: ['Sapa'],
    link: './chi_tiet/MNM203.html',
    destSlug: 'mcc sapa'
  },

  /* ── TÀ XÙA ──────────────────────────────────────────── */
  {
    id: 'MNTX01',
    name: 'Tour Tà Xùa 3N3Đ',
    img: '../images/6_TaXua/MNTX01/MNTX01_01.jpg',
    imgAlt: 'Tour Tà Xùa 3N3Đ',
    duration: '3N3Đ',
    transport: 'Máy bay',
    departure: 'Hồ Chí Minh',
    price: 8228000,
    priceOld: null,
    isHot: false,
    isNew: false,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Tà Xùa',
    otherDests: [],
    link: './chi_tiet/MNTX01.html',
    destSlug: 'taxua'
  },
  {
    id: 'MNTX02',
    name: 'Tour Tà Xùa 2N1Đ',
    img: '../images/6_TaXua/MNTX02/MNTX02_01.jpg',
    imgAlt: 'Tour Tà Xùa 2N1Đ',
    duration: '2N1Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2508000,
    priceOld: null,
    isHot: false,
    isNew: false,
    isSale: false,
    region: 'Tây Bắc',
    primaryDest: 'Tà Xùa',
    otherDests: [],
    link: './chi_tiet/MNTX02.html',
    destSlug: 'taxua'
  },

  /* ── HÀ GIANG ────────────────────────────────────────── */
  {
    id: 'MNHG01',
    name: 'Tour Hà Giang - Sông Nho Quế 5N4Đ',
    img: '../images/7_HaGiang/MNHG01/MNHG01_01.jpg',
    imgAlt: 'Tour Hà Giang - Sông Nho Quế 5N4Đ',
    duration: '5N4Đ',
    transport: 'Máy bay',
    departure: 'Hồ Chí Minh',
    price: 7011000,
    priceOld: 7380000,
    isHot: false,
    isNew: false,
    isSale: true,
    region: 'Đông Bắc',
    primaryDest: 'Hà Giang',
    otherDests: ['Sông Nho Quế'],
    link: './chi_tiet/MNHG01.html',
    destSlug: 'hagiang'
  },
  {
    id: 'MNHG02',
    name: 'Tour Hà Giang – Cao Bằng – Bắc Kạn 5N4Đ',
    img: '../images/7_HaGiang/MNHG02/MNHG02_01.jpg',
    imgAlt: 'Tour Hà Giang – Cao Bằng – Bắc Kạn 5N4Đ',
    duration: '5N4Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 5550000,
    priceOld: null,
    isHot: false,
    isNew: false,
    isSale: false,
    region: 'Đông Bắc',
    primaryDest: 'Hà Giang',
    otherDests: ['Cao Bằng', 'Bắc Kạn'],
    link: './chi_tiet/MNHG02.html',
    destSlug: 'hagiang caobang backan'
  },
  {
    id: 'MNHG03',
    name: 'Tour Hà Giang – Yên Minh – Lũng Cú – Đồng Văn 3N2Đ',
    img: '../images/7_HaGiang/MNHG03/MNHG03_01.jpg',
    imgAlt: 'Tour Hà Giang – Yên Minh – Lũng Cú – Đồng Văn 3N2Đ',
    duration: '3N2Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2680000,
    priceOld: null,
    isHot: true,
    isNew: false,
    isSale: false,
    region: 'Đông Bắc',
    primaryDest: 'Hà Giang',
    otherDests: [],
    link: './chi_tiet/MNHG03.html',
    destSlug: 'hagiang'
  },
  {
    id: 'MNHG04',
    name: 'Tour Đông Bắc: Hà Giang – Hồ Ba Bể – Thác Bản Giốc 5N5Đ',
    img: '../images/7_HaGiang/MNHG04/MNHG04_01.jpg',
    imgAlt: 'Tour Đông Bắc: Hà Giang – Hồ Ba Bể – Thác Bản Giốc 5N5Đ',
    duration: '5N5Đ',
    transport: 'Máy bay',
    departure: 'Hồ Chí Minh',
    price: 9684000,
    priceOld: 10760000,
    isHot: false,
    isNew: false,
    isSale: true,
    region: 'Đông Bắc',
    primaryDest: 'Hà Giang',
    otherDests: ['Bắc Kạn', 'Cao Bằng'],
    link: './chi_tiet/MNHG04.html',
    destSlug: 'hagiang caobang backan'
  },
  {
    id: 'MNHG05',
    name: 'Tour Hà Giang – Hoàng Su Phì – Xín Mần – Bắc Hà 3N2Đ',
    img: '../images/7_HaGiang/MNHG05/MNHG05_01.jpg',
    imgAlt: 'Tour Hà Giang – Hoàng Su Phì – Xín Mần – Bắc Hà 3N2Đ',
    duration: '3N2Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2331000,
    priceOld: 2590000,
    isHot: false,
    isNew: false,
    isSale: true,
    region: 'Xuyên vùng',
    primaryDest: 'Hà Giang',
    otherDests: ['Bắc Hà'],
    link: './chi_tiet/MNHG05.html',
    destSlug: 'hagiang bachha'
  },

  /* ── CAO BẰNG ────────────────────────────────────────── */
  {
    id: 'MNCB01',
    name: 'Tour du lịch Cao Bằng 3N2Đ',
    img: '../images/8_CaoBang/MNCB01/MNCB01_01.jpg',
    imgAlt: 'Tour du lịch Cao Bằng 3N2Đ',
    duration: '3N2Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2450000,
    priceOld: null,
    isHot: false,
    isNew: false,
    isSale: false,
    region: 'Đông Bắc',
    primaryDest: 'Cao Bằng',
    otherDests: [],
    link: './chi_tiet/MNCB01.html',
    destSlug: 'caobang'
  },
  {
    id: 'MNCB02',
    name: 'Tour Cao Bằng – Bắc Kạn – Hồ Ba Bể 3N2Đ',
    img: '../images/8_CaoBang/MNCB02/MNCB02_01.jpg',
    imgAlt: 'Tour Cao Bằng – Bắc Kạn – Hồ Ba Bể 3N2Đ',
    duration: '3N2Đ',
    transport: 'Xe du lịch',
    departure: 'Hà Nội',
    price: 2040000,
    priceOld: 2550000,
    isHot: false,
    isNew: false,
    isSale: true,
    region: 'Đông Bắc',
    primaryDest: 'Cao Bằng',
    otherDests: ['Bắc Kạn'],
    link: './chi_tiet/MNCB02.html',
    destSlug: 'caobang backan'
  }

];